INSERT INTO tb_category (name) VALUES ('LIVOS');
INSERT INTO tb_category (name) VALUES ('Pizza Bacon');
INSERT INTO tb_category (name) VALUES ('Pizza Moda da Casa');
INSERT INTO tb_category (name) VALUES ('Pizza Portuguesa');
INSERT INTO tb_category (name) VALUES ('Risoto de Carne');
INSERT INTO tb_category (name) VALUES ('Risoto Funghi');
INSERT INTO tb_category (name) VALUES ('Macarrão Espaguete');
INSERT INTO tb_category (name) VALUES ('Macarrão Fusili');
INSERT INTO tb_category (name) VALUES ('Macarrão Penne');
INSERT INTO tb_category (name) VALUES ('Macarrão Penne');
INSERT INTO tb_category (name) VALUES ('Macarrão Penne');
INSERT INTO tb_category (name) VALUES ('Macarrão Penne');
INSERT INTO tb_category (name) VALUES ('Macarrão Penne');
INSERT INTO tb_category (name) VALUES ('Macarrão Penne');
INSERT INTO tb_category (name) VALUES ('Macarrão Penne');
INSERT INTO tb_category (name) VALUES ('Macarrão Penne');
INSERT INTO tb_category (name) VALUES ('Macarrão Penne');
INSERT INTO tb_category (name) VALUES ('Macarrão Penne');
INSERT INTO tb_category (name) VALUES ('Macarrão Penne');
INSERT INTO tb_category (name) VALUES ('Macarrão Penne');
INSERT INTO tb_category (name) VALUES ('Macarrão Penne');
INSERT INTO tb_category (name) VALUES ('Macarrão Penne');
INSERT INTO tb_category (name) VALUES ('Macarrão Penne');
INSERT INTO tb_category (name) VALUES ('Macarrão Penne');
INSERT INTO tb_category (name) VALUES ('Macarrão Penne');
INSERT INTO tb_category (name) VALUES ('Macarrão Penne');
INSERT INTO tb_category (name) VALUES ('Macarrão Penne');
INSERT INTO tb_category (name) VALUES ('Macarrão Penne');
